language: python
sudo: required
python:
  - "2.7"
addons:
    code_climate:
        repo_token: ecea6376557adb6628bbcb5d302a5da95ae37126fe939b0ea8d2757f8da0eefa
before_install:
  - ./setup-apt.sh
virtualenv:
  system_site_packages: true
script:
  - cd Client-Python
  - python Test.py
  - cd ../Server
  - python Test.py
  - cd ..
after_success:
- nosetests
