language: python
sudo: required
python:
  - "2.7"
before_install:
  - wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.18.1/sip-4.18.1.tar.gz
  - tar zxvf sip-4.18.1.tar.gz
  - cd sip-4.18.1/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'
  - wget http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz
  - tar zxvf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4/
  - echo 'yes' | python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import PyQt4'
  - python -c 'import PyQt4.QtCore'
script:
  - python Client-Python/Test.py
  - python Server/Test.py
after_success:
- nosetests
