language: python
sudo: required
python:
  - "2.7"
#install:
  #- pip install setuptools
  #- pip install pyaudio
script:
  - python Client-Python/client.py
  - python Server/server.py
after_success:
- nosetests
