language: go

go:
  - tip

before_install:
  # lint
  - go get github.com/golang/lint/golint

  # code complexity
  - go get github.com/on99/gocyclo

  # setup for boe
  - make setup

script:
  - golint ./...
  - go vet ./...
  - gocyclo -skip-godeps=true -top 10 -over 10 . # over 10 is consittered bad code
