language: python
sudo: required
python:
  - "2.7"
#install:
  #- pip install setuptools
  #- pip install pyaudio
script:
  - python Client-Python/Test.py
  - python Server/Test.py
after_success:
- nosetests
