language: python
sudo: required
python:
  - "2.7"
before_install:
  - wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.18.1/sip-4.18.1.tar.gz
  - tar zxvf sip-4.18.1.tar.gz
  - cd sip-4.18.1/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'
  - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
  - python -c 'import PyQt4'
  - python -c 'import PyQt4.QtCore'
script:
  - python Client-Python/Test.py
  - python Server/Test.py
after_success:
- nosetests
